[build]
  command = "npm install --force && npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  NODE_VERSION = "18.20.5"
  NPM_VERSION = "10.8.2"
  SKIP_PREFLIGHT_CHECK = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200