[build]
  command = "CI=false npm install --legacy-peer-deps && CI=false npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  NODE_VERSION = "16.20.0"
  NPM_VERSION = "8.19.4"
  SKIP_PREFLIGHT_CHECK = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https://imagedelivery.net https://placehold.co https://www.googletagmanager.com blob:https://market.bagasi.id https://static.chemistwarehouse.com.au; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://api.bagasi.id https://api.stripe.com;"