[build]
  command = "CI=false npm install --legacy-peer-deps && CI=false npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  NODE_VERSION = "16.20.0"
  NPM_VERSION = "8.19.4"
  SKIP_PREFLIGHT_CHECK = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200